# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Fawaz Alsaif
description: "A versatile professional with over a decade in Oil & Gas, I am passionate about using my expertise to drive impact across various industries. With a strong foundation in operations management, supply chain and Lean & Six Sigma, my knowledge in Waterfall Project Management, Agile and Scrum frameworks complements my ability to lead cross-functional teams and navigate complex projects.

With an unwavering commitment to staying current in my field, I continually seek opportunities to enhance my skills and knowledge to maintain a competitive edge in today's fast-paced business landscape. I am eager to connect and collaborate with those who seek to leverage data-driven insights to achieve exceptional results."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science/Analytics <span style="color:#f58506"> Portfolio </span>
location: "Kuwait"
resume_url: /img/Fawaz_alsaif_resume.pdf
avatar_image: /img/fawaz-alsaif.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/fawazalsaif/" # Add your linkedln handle
github: "https://github.com/fawaz-alsaif"  # Add your github handle

paginate: 10
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

